// <auto-generated />
using LinePlaneCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LinePlaneCore.Migrations.User
{
    [DbContext(typeof(UserContext))]
    [Migration("20210420232354_UserTableCreated")]
    partial class UserTableCreated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LinePlaneCore.User", b =>
                {
                    b.Property<string>("_Login")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("_Password")
                        .HasColumnType("int");

                    b.HasKey("_Login");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
