// <auto-generated />
using LinePlaneCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LinePlaneCore.Migrations
{
    [DbContext(typeof(LinePlaneContext))]
    [Migration("20210503200445_TableCreated3")]
    partial class TableCreated3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LinePlaneCore.Furniture", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("_FurnitureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("_IdTipeFurniture")
                        .HasColumnType("int");

                    b.Property<string>("_Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("_Price")
                        .HasColumnType("int");

                    b.HasKey("_Id");

                    b.HasIndex("_IdTipeFurniture");

                    b.ToTable("Furnitures");
                });

            modelBuilder.Entity("LinePlaneCore.Measurements", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("_IdFurniture")
                        .HasColumnType("int");

                    b.Property<string>("_Length")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_Width")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("_IdFurniture");

                    b.ToTable("Measurments");
                });

            modelBuilder.Entity("LinePlaneCore.Model.Server.Conservation", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("_FurnitureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_IdUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("_Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("_Id");

                    b.HasIndex("_IdUser");

                    b.ToTable("Conservations");
                });

            modelBuilder.Entity("LinePlaneCore.Model.Server.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("_IdConservation")
                        .HasColumnType("int");

                    b.Property<int>("_IdFurniture")
                        .HasColumnType("int");

                    b.Property<int>("_IdMeasurements")
                        .HasColumnType("int");

                    b.Property<int>("_IdWall")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("_IdConservation");

                    b.HasIndex("_IdMeasurements");

                    b.HasIndex("_IdWall");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("LinePlaneCore.TipeFurniture", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FurnitureTipe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("_Id");

                    b.ToTable("TipeFurnitures");
                });

            modelBuilder.Entity("LinePlaneCore.User", b =>
                {
                    b.Property<string>("_Login")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("_Password")
                        .HasColumnType("int");

                    b.HasKey("_Login");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LinePlaneCore.Wall", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("_X1")
                        .HasColumnType("int");

                    b.Property<int>("_X2")
                        .HasColumnType("int");

                    b.Property<int>("_Y1")
                        .HasColumnType("int");

                    b.Property<int>("_Y2")
                        .HasColumnType("int");

                    b.HasKey("_Id");

                    b.ToTable("Walls");
                });

            modelBuilder.Entity("LinePlaneCore.Furniture", b =>
                {
                    b.HasOne("LinePlaneCore.TipeFurniture", "_TipeFurniture")
                        .WithMany()
                        .HasForeignKey("_IdTipeFurniture")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_TipeFurniture");
                });

            modelBuilder.Entity("LinePlaneCore.Measurements", b =>
                {
                    b.HasOne("LinePlaneCore.TipeFurniture", "_Furniture")
                        .WithMany()
                        .HasForeignKey("_IdFurniture")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_Furniture");
                });

            modelBuilder.Entity("LinePlaneCore.Model.Server.Conservation", b =>
                {
                    b.HasOne("LinePlaneCore.User", "_User")
                        .WithMany()
                        .HasForeignKey("_IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_User");
                });

            modelBuilder.Entity("LinePlaneCore.Model.Server.Project", b =>
                {
                    b.HasOne("LinePlaneCore.Model.Server.Conservation", "_Conservation")
                        .WithMany()
                        .HasForeignKey("_IdConservation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinePlaneCore.Measurements", "_Measurements")
                        .WithMany()
                        .HasForeignKey("_IdMeasurements")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinePlaneCore.Wall", "_Wall")
                        .WithMany()
                        .HasForeignKey("_IdWall")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_Conservation");

                    b.Navigation("_Measurements");

                    b.Navigation("_Wall");
                });
#pragma warning restore 612, 618
        }
    }
}
